Bump to v2.3.1 - Drop Illumos support per policy in #711 (#1503)
* Drop Illumos support per policy in #711

In https://github.com/openbao/openbao/actions/runs/15883186152/job/44788865022,
the Illumos build failed. This was due to the etcd build failing:

>     • building                                       build={builds-other [illumos] [amd64 arm arm64 riscv64] [v1] [sse2] [6 7] [v8.0] [hardfloat] [power8] [rva20u64] [illumos_amd64_v1] [{linux        } {darwin    6    } {darwin arm       } {darwin riscv64       } {dragonfly arm       } {dragonfly arm64       } {dragonfly riscv64       } {freebsd    7    } {illumos arm       } {illumos arm64       } {netbsd riscv64       } {netbsd    7    } {openbsd riscv64       } {openbsd    7    } {windows arm   7    } {windows riscv64       }] . . bao {[] []} go {{ .CommitTimestamp }} false  go build  false   { [-X github.com/openbao/openbao/version.fullVersion={{.Version}} -X github.com/openbao/openbao/version.GitCommit={{.Commit}} -X github.com/openbao/openbao/version.BuildDate={{ .Date }}] [ui] [] [] [] [CGO_ENABLED=0]} []}
>     • building                                       binary=dist/builds-other_illumos_amd64_v1/bao
>     • env "CGO_ENABLED=0" evaluated to "CGO_ENABLED=0"
>     • running
>     • took: 2m0s
>   ⨯ release failed after 2m29s               error=build failed: failed to build for illumos_amd64_v1: exit status 1: # go.etcd.io/bbolt
> Error: ../../../go/pkg/mod/go.etcd.io/bbolt@v1.4.1/bolt_solaris.go:70:15: undefined array length maxMapSize or missing type constraint
>
> target: illumos_amd64_v1
> Error: Process completed with exit code 1.

If this is fixed with a corresponding action build + test verification,
we can revert this.

See also: https://github.com/etcd-io/bbolt/pull/988

Signed-off-by: Alexander Scheel <ascheel@gitlab.com>

* Bump changelog version to v2.3.1

Signed-off-by: Alexander Scheel <ascheel@gitlab.com>

---------

Signed-off-by: Alexander Scheel <ascheel@gitlab.com>