Fix compatibility with Go 1.27rc2 (#3752)
* Update t.Fatalf to work with Go 1.27

The %q directive no longer works with non-string values in tests.

Signed-off-by: Alexander Scheel <alex.scheel@control-plane.io>

* Bump MySQL container to 9.0

This fixes a TLS connection error:

    [mysql] 2026/08/10 10:12:51 packets.go:58 unexpected EOF
    --- FAIL: TestInit_clientTLS (12.10s)
        connection_producer_test.go:85: Unable to initialize mysql engine: error verifying - ping: TLS requested but server does not support TLS
    [mysql] 2026/08/10 10:12:58 packets.go:58 unexpected EOF

and suggests that older MySQL versions are not compatible with the
upcoming Go 1.27's TLS cipher suite changes.

Signed-off-by: Alexander Scheel <alex.scheel@control-plane.io>

* Remove trailing dot in FQDNs

In Go 1.27, we now see:

> idna: invalid label "example.com."

due to the trailing dot. This does not have a changelog in the current
Go 1.27 release notes.

Resolves: #3751

Signed-off-by: Alexander Scheel <alex.scheel@control-plane.io>

* Add changelog entry

Signed-off-by: Alexander Scheel <alex.scheel@control-plane.io>

---------

Signed-off-by: Alexander Scheel <alex.scheel@control-plane.io>