Revert "Bump actions/download-artifact from 3.0.2 to 4.1.4"
This reverts commit 1d0b2ddff3e75399a47af36509a35b36ef39590c. When
accepting the commit from https://github.com/openbao/openbao/pull/125,
this causes failures in the pipeline like:

> Error: Failed to CreateArtifact: Received non-retryable error:
>        Failed request:
>               (409) Conflict: an artifact with this name already
>                               exists on the workflow run

So likely we've fallen into the breaking change section of v3->v4
behavior. Some investigation will be needed to determine what to change
to fix this issue.

Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>