Bump grpc, edwards25519 dependencies (#2738)
See output from `make vulncheck`:

    === Symbol Results ===

    Vulnerability #1: GO-2026-4762
        Authorization bypass in gRPC-Go via missing leading slash in :path in
        google.golang.org/grpc
      More info: https://pkg.go.dev/vuln/GO-2026-4762
      Module: google.golang.org/grpc
        Found in: google.golang.org/grpc@v1.79.2
        Fixed in: google.golang.org/grpc@v1.79.3
        Example traces found:
    Error:       #1: command/agent.go:799:17: command.AgentCommand.Run calls run.Group.Run, which eventually calls grpc.Server.Serve
    Error:       #2: vault/forwarding/request_forwarding.go:206:19: forwarding.Handoff calls http2.Server.ServeConn, which eventually calls grpc.Server.ServeHTTP

    === Package Results ===

    Vulnerability #1: GO-2026-4503
        Invalid result or undefined behavior in filippo.io/edwards25519
      More info: https://pkg.go.dev/vuln/GO-2026-4503
      Module: filippo.io/edwards25519
        Found in: filippo.io/edwards25519@v1.1.0
        Fixed in: filippo.io/edwards25519@v1.1.1

Signed-off-by: Alexander Scheel <alex.scheel@control-plane.io>